name: Jest Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2

    - name: Use Node.js
      uses: actions/setup-node@v2.4.2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install

    - name: Run Jest Tests
      run: npm test